[package]
name = "klee-rs"
version = "0.0.0"
authors = ["Mark Hakansson <mark.hakansson@live.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
klee-bindings = { path = "klee-bindings/" }
libc = "0.2.0"
